apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helloworld

commonLabels:
  app: helloworld

configMapGenerator:
- name: ingress-properties
  literals:
  - HOST=my.host.domain.name.tld

# comment out if TLS should be used
# requires cert-manager-app
patches:
- patch: |-
    - op: remove
      path: /spec/tls
  target:
    kind: Ingress
    version: v1
    group: networking.k8s.io
    name: helloworld
- patch: |-
    - op: add
      path: /spec/template/metadata/annotations
      value:
        linkerd.io/inject: enabled
  target:
    kind: Deployment
    version: v1
    group: apps
    name: helloworld

vars:
- name: HOST
  objref: { kind: ConfigMap, name: ingress-properties, apiVersion: v1 }
  fieldref: { fieldpath: data.HOST }

resources:
- ./0-namespace.yaml
- ./manifests.yaml

