apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: ingress-properties
  literals:
  - HOST=my.host.domain.name.tld

# comment out if TLS should be used
# requires cert-manager-app
patches:
- patch: |-
    - op: remove
      path: /spec/tls
  target:
    kind: Ingress
    version: v1
    group: networking.k8s.io
    name: helloworld

vars:
- name: HOST
  objref: { kind: ConfigMap, name: ingress-properties, apiVersion: v1 }
  fieldref: { fieldpath: data.HOST }

resources:
- ./manifests.yaml

